force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Domain_Config__mdt/Domain_Config__mdt.object-meta.xml
<CustomObject>
    <label>Domain Config</label>
    <pluralLabel>Domain Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Domain_Config__mdt/fields/Bypass_Error_Handling__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Error_Handling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Error Handling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Domain_Config__mdt/fields/Bypass_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Domain_Config__mdt/fields/Prevent_Recursion__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Recursion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prevent Recursion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FFLIB/TriggerHandlers/BoardGameRatingsTriggerHandler.cls
//Needs to Implement and Extend the fflib_SObjectDomain and fflib_ISObjectDomain respecively in order to mock the Domain
//IBoardGameRatingsDomain extends fflib_ISObjectDomain but can add other methods onto it if needed
public with sharing class BoardGameRatingsTriggerHandler extends fflib_SObjectDomain implements fflib_ISObjectDomain{
    
    @TestVisible
    private Domain_Config__mdt domainConfig;

    //Actual Constructor for the Domain
    public BoardGameRatingsTriggerHandler(List<Board_Game_Rating__c> sObjectList){
        //Get Custom Metadata Type for Domain
        this(Domain_Config__mdt.getInstance('BoardGameRatings'), sObjectList);
    }

    @TestVisible
    //Constructor Used For Testing and Setting Own Config File
    private BoardGameRatingsTriggerHandler(Domain_Config__mdt config, List<Board_Game_Rating__c> sObjectList)
    {
        super(sObjectList);
        domainConfig = config;

        //Disable Triggers, if enabled 
        If(domainConfig.Bypass_Trigger__c){
            system.debug('Disabling Trigger...');
            fflib_SObjectDomain.getTriggerEvent(BoardGameRatingsDomain.class).disableAll();
        }
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        //Initialize Unit of Work and Service Classes from Application Layer
        fflib_SObjectUnitOfWork uow = (fflib_SObjectUnitOfWork) Application.UnitOfWork.newInstance();
        BoardGameRatingsService service = (BoardGameRatingsService) Application.Service.newInstance(IBoardGameRatingsService.class);

        //Prevent Recursion on After Update, If enabled
        if(domainConfig.Prevent_Recursion__c)
        {
            system.debug('Disabling Trigger For Recursion ...');
            fflib_SObjectDomain.getTriggerEvent(BoardGameRatingsDomain.class).disableAfterUpdate(); 
        }

        try{         
            //Do Work

            //super.Records gets all of the Records from the trigger from the Domain
            service.setNewFavorite(uow, super.Records, existingRecords); 

            //Perform DML on all Registered Records
            uow.commitWork();
        }
        catch (Exception ex) 
        {
            //Bypass Error Handling, If Enabled
            if(domainConfig.Bypass_Error_Handling__c)
            {
                System.debug('An Error Occured: ' + ex.getMessage());
            }
            else 
            {
                throw new BRGDomainException('An Error Occured in the Board Game Ratings Domain: ' + ex.getMessage());
            }
        }
    }

    public class BRGDomainException extends Exception {}

}