force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Game_Rating__c/fields/Board_Game__c.field-meta.xml
<CustomField>
    <fullName>Board_Game__c</fullName>
    <description>Board Game Being Rated</description>
    <inlineHelpText>Board Game Being Rated</inlineHelpText>
    <label>Board Game</label>
    <referenceTo>Board_Games__c</referenceTo>
    <relationshipLabel>Board Game Ratings</relationshipLabel>
    <relationshipName>Board_Game_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Board_Game_Rating__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Ratings</relationshipLabel>
    <relationshipName>Board_Game_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Board_Game_Rating__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/Board_Games__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Individual Board Games.</description>
    <label>Board Game</label>
    <nameField>
        <label>Board Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FFLIB/Selectors/BoardGameRatingSelector.cls
@SuppressWarnings('PMD.SOQLInjection') //PMD Incorrectly identifies Queries made in Selectors to have possible SOQL Injection. This Suppresses that Warning
//Without Sharing is needed in order to always return all values of a query
public without sharing class BoardGameRatingSelector extends fflib_SObjectSelector implements IBoardGameRatingSelector  {
    
    //Required Method to Initialize Selector
    public static IBoardGameRatingSelector newInstance() {
        return (IBoardGameRatingSelector) Application.Selector.newInstance(Board_Game_Rating__c.SObjectType);
    }

    //Required Method to Determine SObject Type
    public Schema.SObjectType getSObjectType() {
        return Board_Game_Rating__c.SObjectType;
    }

    //Required Method. Used to get Fields from Object needed in any Selector Method
    //Add Fields to List as Needed.
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Board_Game_Rating__c.Board_Game__c,
            Board_Game_Rating__c.Event_Attendee__c,
            Board_Game_Rating__c.is_Favorite__c
        };
    }
    
    //Standard Method. Basic Select By ID Query (From Parent fflib_SObjectSelector)
    public List<Board_Game_Rating__c> selectById(Set<Id> recordIds){
        // Optionally, this method can just use and return the line:
        return super.selectSObjectsById(recordIds);
        //If Any Customization is needed for this method, replace this with a normal QueryFactory Query
    }
    
    //Names of Selector Methods Should describe all of the Conditions for the Query
    //Return Value should always be a List of the Selector's Object
    //Input Parameters should always be Sets of the value type for bulkificationa and resuability
    public List<Board_Game_Rating__c> selectFavoriteRatingByUserIdExcludingRecordID(Set<Id> attendeeIds, Set<Id> excludeRecordIds){

        // Query Factory Options (Optional):
        // AssertCRUD: False By Default, Determines if CRUD Permissions are Enforced.
        // enforceFLS: False By Default, Determines if Field Level Secrity is Enforced.
        // includeSelectorFields: True By Default, Query Uses Fields from getSObjectFieldList Method. Disable to limit to only own selected fields

        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Board_Game__r.Name'); //selectField is Only way to include fields from Parent Objects
        query.setCondition('Event_Attendee__c = :attendeeIds '
                            + ' AND ID != :excludeRecordIds '
                            + ' AND is_Favorite__c = true');
        return (List<Board_Game_Rating__c>) Database.query(query.toSOQL());
    }
}