force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Game_Rating__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Ratings</relationshipLabel>
    <relationshipName>Board_Game_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Board_Game_Rating__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Domain_Config__mdt/Domain_Config__mdt.object-meta.xml
<CustomObject>
    <label>Domain Config</label>
    <pluralLabel>Domain Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Services_Config__mdt/Services_Config__mdt.object-meta.xml
<CustomObject>
    <label>Services Config</label>
    <pluralLabel>Services Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Services_Config__mdt/fields/Domain_Config__c.field-meta.xml
<CustomField>
    <fullName>Domain_Config__c</fullName>
    <label>Domain Config</label>
    <referenceTo>Domain_Config__mdt</referenceTo>
    <relationshipLabel>Services Configs</relationshipLabel>
    <relationshipName>Services_Configs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Services_Config__mdt/fields/Service_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Service_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FFLIB/Services/BoardGameRatingsService.cls
public without sharing class BoardGameRatingsService implements IBoardGameRatingsService {
    
    //Set Variables used throughout Service
    @TestVisible 
    private Map<String, Services_Config__mdt> serviceConfigMap = new Map<String, Services_Config__mdt>(); 
    private BoardGameRatingSelector bgRatingSelector;

    //Initialize Service Class
    public BoardGameRatingsService(){
        this(Services_Config__mdt.getAll().values());
    }

    @TestVisible
    //Private Constructor for Testing to provide own Service Config
    private BoardGameRatingsService(List<Services_Config__mdt> configList){
        //Initialize Selectors
        bgRatingSelector = (BoardGameRatingSelector) BoardGameRatingSelector.newInstance();
        
        //Get All Service Config Records without SOQL Call, Filter By Domain
        for(Services_Config__mdt config : configList){
            if(config.Domain_Config__r.DeveloperName == 'BoardGameRatingsDomain'){
                serviceConfigMap.put(config.DeveloperName, config);
            }
        }
    }

    public void setNewFavorite(fflib_SObjectUnitOfWork uow, List<Board_Game_Rating__c> newRecords, Map<Id,SObject> existingRecords){
        
        //If Service Config for Method Found AND Service Method is Enabled
        if(serviceConfigMap.containsKey('setNewFavorite') 
            && serviceConfigMap.get('setNewFavorite').Service_Enabled__c){

                //Creat Map where the Attendee ID will be the Key and the Rating Id will be the value
                Map<Id, Id> favRatingMap = new Map<Id, Id>();

                //We must treat the records being passed in as if it was done in bulk
                //For Each Rating is Records,
                for(Board_Game_Rating__c thisRating : newRecords){
                    //If IsFavorite Changed To Checked on Record
                    If(!((Board_Game_Rating__c) existingRecords.get(thisRating.Id)).is_Favorite__c
                        && thisRating.is_Favorite__c){
                        
                        //Check if Attendee Fav not yet added
                        If(!favRatingMap.containsKey(thisRating.Event_Attendee__c)){
                            //Place Fav Record ID into Map using the Attendee ID as key
                            favRatingMap.put(thisRating.Event_Attendee__c, thisRating.Id);
                        }
                        else {
                            //Throw Exception for Duplicate Favorites in the same update
                            throw new BGRServiceException('Duplicate Favorite Found');
                        }   

                    }
                }

                //If Fav Ratings were Found
                if(favRatingMap != null){
                    // Get All Favorite Ratings for All Attendees in update that marked the record as Favorite, 
                    // Excluding the Favorited Records
                    for(Board_Game_Rating__c thisRating : bgRatingSelector.selectFavoriteRatingByAttendeeIdExcludingRecordID(
                                                                            favRatingMap.keySet(), 
                                                                            new Set<Id>(favRatingMap.values())
                                                                        )){
                        thisRating.is_Favorite__c = false; //Set Each Rating As False
                        uow.registerDirty(thisRating); //Register Rating to be Updated, No DML Performed yet
                    }
                }
        }
    }

    public class BGRServiceException extends Exception {}
}