force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game_Rating__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Event Attendee Rating the Board Game</description>
    <inlineHelpText>Event Attendee Rating the Board Game</inlineHelpText>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Ratings</relationshipLabel>
    <relationshipName>Board_Game_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game_Rating__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Mark this game as Favorite for Event Attendee. Attendees can only have one Favorite</description>
    <inlineHelpText>Check to mark this Board Game as your favorite. (Limit 1)</inlineHelpText>
    <label>Is Favorite</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/fflib-working-examples/main/classes/actions/SetFavoriteBoardGameRatingAfterAction.cls
public without sharing class SetFavoriteBoardGameRatingAfterAction extends AbstractBaseDomainProcessAction {
    public override void runInProcess(){

        //Filter records for those where Is Favorite is changed
        List<Board_Game_Rating__c> records = (List<Board_Game_Rating__c>) this.getChanged('Is_Favorite__c');
        //If No Favorited Records provided, Do Nothing
        if(records.size() == 0){
            return;
        }

        BoardGameRatingSelector bgRatingSelector = (BoardGameRatingSelector) Application.Selector.newInstance(Board_Game_Rating__c.sObjectType);
        //Create Map where the Attendee ID will be the Key and the Rating Id will be the value
        Map<Id, Id> favRatingMap = new Map<Id, Id>();

        //We must treat the records being passed in as if it was done in bulk
        //For Each Rating is Records,
        for(Board_Game_Rating__c thisRating : records){

            //Check if Attendee Fav not yet added
            If(!favRatingMap.containsKey(thisRating.Event_Attendee__c)){
                //Place Fav Record ID into Map using the Attendee ID as key
                favRatingMap.put(thisRating.Event_Attendee__c, thisRating.Id);
            }
            else {
                //Throw Exception for Duplicate Favorites in the same update
                throw new BGRActionException('Duplicate Favorite Found');
            }   
        }

        // Get All Favorite Ratings for All Attendees in update that marked the record as Favorite, 
        // Excluding the Favorited Records
        for(Board_Game_Rating__c thisRating : bgRatingSelector.selectFavoriteRatingByAttendeeIdExcludingRecordID(
                                                                favRatingMap.keySet(), //Attendee IDs
                                                                new Set<Id>(favRatingMap.values()) //Exclude these Ratings IDs
                                                            )){
            thisRating.is_Favorite__c = false; //Set Each Rating As False
            uow.registerDirty(thisRating); //Register Rating to be Updated, No DML Performed yet
        }

        this.uow.commitWork();
    }

    public class BGRActionException extends Exception {}
}