force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Game_Rating__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Ratings</relationshipLabel>
    <relationshipName>Board_Game_Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Board_Game_Rating__c/fields/Is_Favorite__c.field-meta.xml
<CustomField>
    <fullName>Is_Favorite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Favorite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FFLIB/Selectors/BoardGameRatingSelectorTest.cls
@isTest
private class BoardGameRatingSelectorTest {
    
    @IsTest
    //Standard Test Method to Test NewInstance Method, Also covers getSObjectType Method
    //getSObjectFieldList Method is covered and called by Standard Selector Methods so no indiviual Unit Test is Needed
    public static void newInstance_shouldReturnInstance() {

        Test.startTest();
        IBoardGameRatingSelector result = BoardGameRatingSelector.newInstance();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Should return instance');
    }

    @isTest
    //Standard Test Method for Select By ID Method
    public static void givenBGRFavoriteRecord_WhenSelectByIDisCalled_ThenReturnCorrectRecord() {
        
        //Create Test Data (Use Test Util Class where possible)
        Board_Game_Rating__c testRecord = TestUtil.createBoardGameRating();
        insert testRecord; 

        //Perform Test
        Test.startTest();
        List<Board_Game_Rating__c> results = BoardGameRatingSelector.newInstance().selectById(new Set<Id>{testRecord.Id});
        Test.stopTest();

        //Validate Data
        Assert.areEqual(1, results.size(), 'No Results Returned for Test Record ID');
        Assert.areEqual(testRecord.Id, results[0].Id, 'Record Returned does not match Test Record');
    }

    //Additional Test Methods for Selector Methods
    @isTest
    public static void givenBGRFavoriteRecord_WhenSelectFavoriteRatingByAttendeeIdExcludingRecordIDisCalled_ThenReturnResults() {
        
        //Create Test Data (Use Test Util Class where possible)
        Board_Game_Rating__c testRecord = TestUtil.createBoardGameRating();
        testRecord.is_Favorite__c = true;
        insert testRecord;

        //Perform Test
        Test.startTest();
        List<Board_Game_Rating__c> results = BoardGameRatingSelector.newInstance().selectFavoriteRatingByAttendeeIdExcludingRecordID(new Set<Id>{testRecord.Event_Attendee__c}, 
                                                                                                                                    //Generate ID that is NOT the TestRecord ID
                                                                                                                                    new Set<Id>{fflib_IDGenerator.generate(Board_Game_Rating__c.SObjectType)});
        Test.stopTest();

        //Validate Data
        Assert.areEqual(1, results.size(), 'No Results Returned for Test Record ID');
        Assert.areEqual(testRecord.Id, results[0].Id, 'Record Returned does not match Test Record');    
    }
}