force-app/main/default/objects/BG_Library_Entry__c/BG_Library_Entry__c.object-meta.xml
<CustomObject>
    <description>Since a Board Game can be used in Many Events and Events can Have Many Board Games, this Object is used to Join the two Objects together</description>
    <label>Board Game Library Entry</label>
    <nameField>
        <displayFormat>EBD-{000000}</displayFormat>
        <label>Library Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Library Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Library_Entry__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Board Games</relationshipLabel>
    <relationshipName>Event_Board_Games</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Board_Game_Rating__c/Board_Game_Rating__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Ratings Event Attendees submit for games they have played</description>
    <label>Board Game Rating</label>
    <nameField>
        <displayFormat>BGR-{000}</displayFormat>
        <label>Board Game Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Games__c/Board_Games__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Individual Board Games.</description>
    <label>Board Game</label>
    <nameField>
        <label>Board Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This is the Description for the Event Object</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FFLIB/Application/Application.cls
/**
 * FFLIB Application Layer
 * Used to quickly generate the Factories for the Service, Selector, UnitOfWork, and Domain Layers.
 * Another benefit of using the Application Layer is that it can be used during mocking and stubbing to replace these Layers
 * when called by the Apex classes during testing so that to allow for pure Unit Testing of the function being tested without 
 * dependancies from other methods or validation of data not needed for the test.
 */
public class Application {
    /** Configure and create the ServiceFactory for this Application 
     * Service Layer: This layer handles all of the business logic for a method call from the Domain, usually passing in a 
     *  UnitOfWork object as a parameter so that all DML transactions are handled once the trigger completes.  
     *  The benefit is that the method can be unit tested without actually performing any DML and instead inspecting the 
     *  UnitOfWork object to see if it contains the expected records that were inserted, updated or deleted.
     * Recommended Naming Convention for the Service Class is [SObjectName]sService so it is clear it is the Service Class for that SObject
    */
    public static final fflib_Application.ServiceFactory Service = new fflib_Application.ServiceFactory(
        new Map<Type, Type>{
            //Mapped By Interface as Key
            //Addtional SObject Service Classes Go Here 
            IBoardGameRatingsService.class => BoardGameRatingsService.class,
            IBoardGamesService.class => BoardGamesService.class,
            IBGGCalloutService.class => BGGCalloutService.class
        }
    );

    /** Configure and create the SelectorFactory for this Application
     * Selector Layer: This layer handles all of the SOQL Calls for an object. 
     *  The benefit is that during testing the Selector can be mocked and stubbed out so that the unit tests can focus on the method 
     *  without creating a bunch of Test Data with prerequisites and validations first.
     * Recommended Naming Convention for the Selector Class in [SObjectName]Selector so it is clear it is the Selector Class for that SObject
    */
    public static final fflib_Application.SelectorFactory Selector = new fflib_Application.SelectorFactory(
        new Map<SObjectType, Type>{
            // Map SObjectType to Selector Class
            //Additional SObject Selectors Go Here
            Board_Game_Rating__c.SObjectType => BoardGameRatingSelector.class,
            Event__c.SObjectType => EventSelector.class,
            Board_Games__c.SObjectType => BoardGameSelector.class
        }
    );

    /** Configure and create the DomainFactory for this Application
    *  Domain Layer: This layer handles all of the trigger actions for the Object such as before and after insert update and delete methods
    *  Recommended Naming Convention for the Domain Class in [SOBjectName]sDomain so it is clear it is the Domain Class for that SObject  
    */
    public static final fflib_Application.DomainFactory Domain = new fflib_Application.DomainFactory(
        Application.Selector,
        // Map SObjectType to Domain Class Constructors
        new Map<SObjectType, Type>{
            //Additional SObject Domains Go Here
            Board_Game_Rating__c.SObjectType => BoardGameRatingsDomain.Constructor.class
        }
    );

    /** Configure and create the UnitOfWorkFactory for this Application
    *  UnitOfWork Layer: This layer handles all of the DML transactions for the Methods and commits all changes 
    *   to SObjects at the same time using minimal DML Calls
    *  NOTE: SObjects will be inserted and updated in the order in which they appear in this list so Child Objects must be below the Parent Object 
    *  Example: Since Account is the Parent Object to Contact, Account must be listed above Contact.
    */ 
    public static final fflib_Application.UnitOfWorkFactory UnitOfWork = new fflib_Application.UnitOfWorkFactory(
        new List<SObjectType>{
            //Additional SObjectTypes for Unit Of Work Go Here with Parent Objects Above Child
            Board_Game_Rating__c.SObjectType,
            Board_Games__c.SObjectType,
            BG_Library_Entry__c.SObjectType
        }
    );
}