force-app/main/default/objects/BG_Checkout_Log__c/BG_Checkout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about each time a board game was checked out and back in</description>
    <label>Board Game Checkout Log</label>
    <nameField>
        <displayFormat>BGL-{000000}</displayFormat>
        <label>Board Game Checkout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Checkout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Checkout_Log__c/fields/BG_Library_Entry__c.field-meta.xml
<CustomField>
    <fullName>BG_Library_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library Entry</label>
    <referenceTo>BG_Library_Entry__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Library_Entry__c/BG_Library_Entry__c.object-meta.xml
<CustomObject>
    <description>Since a Board Game can be used in Many Events and Events can Have Many Board Games, this Object is used to Join the two Objects together</description>
    <label>Board Game Library Entry</label>
    <nameField>
        <displayFormat>EBD-{000000}</displayFormat>
        <label>Library Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Library Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Library_Entry__c/fields/Board_Game__c.field-meta.xml
<CustomField>
    <fullName>Board_Game__c</fullName>
    <label>Board Game</label>
    <referenceTo>Board_Games__c</referenceTo>
    <relationshipLabel>Event Board Games</relationshipLabel>
    <relationshipName>Event_Board_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FFLIB Examples/Selectors/Tests/BGCheckOutLogSelectorTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Test Class for the Check Out Log Selector
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2025-02-05
* @modified       2025-02-05
* @systemLayer    Test
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
private class BGCheckOutLogSelectorTest {
    
    @IsTest
    //Standard Test Method to Test NewInstance Method, Also covers getSObjectType Method
    //getSObjectFieldList Method is covered and called by Standard Selector Methods so no indiviual Unit Test is Needed
    public static void newInstance_shouldReturnInstance() {

        Test.startTest();
        IBGCheckOutLogSelector result = BGCheckOutLogSelector.newInstance();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Should return instance');
    }

    @isTest
    //Standard Test Method for Select By ID Method
    public static void givenLogID_WhenSelectByIdIsCalled_ThenReturnCorrectRecord() {
        
        //Create Test Data (Use Test Util Class where possible)
        BG_Checkout_Log__c testRecord = TestUtil.createBoardGameCheckOutLog();
        insert testRecord; 

        //Perform Test
        Test.startTest();
        List<BG_Checkout_Log__c> results = BGCheckOutLogSelector.newInstance().selectById(new Set<Id>{testRecord.Id});
        Test.stopTest();

        //Validate Data
        Assert.areEqual(1, results.size(), 'No Results Returned for Test Record ID');
        Assert.areEqual(testRecord.Id, results[0].Id, 'Record Returned does not match Test Record');
    }

    //Additional Test Methods for Selector Methods

    @isTest
    public static void givenBoardGameId_WhenSelectByBoardGameIdIsCalled_ThenReturnCorrectRecord() {
        
        //Create Test Data (Use Test Util Class where possible)
        BG_Library_Entry__c testBGLE = TestUtil.createBoardGameLibraryEntry();
        insert testBGLE;

        BG_Checkout_Log__c testRecord = TestUtil.createBoardGameCheckOutLog(testBGLE.Id);
        insert testRecord; 

        //Perform Test
        Test.startTest();
        List<BG_Checkout_Log__c> results = BGCheckOutLogSelector.newInstance().selectByBoardGameId(new Set<Id>{testBGLE.Board_Game__c});
        Test.stopTest();

        //Validate Data
        Assert.areEqual(1, results.size(), 'No Results Returned for Test Record ID');
        Assert.areEqual(testRecord.Id, results[0].Id, 'Record Returned does not match Test Record');
    }

    @isTest
    public static void givenBGLEId_WhenSelectByLibraryEntryIdIsCalled_ThenReturnCorrectRecord() {
        
        //Create Test Data (Use Test Util Class where possible)
        BG_Checkout_Log__c testRecord = TestUtil.createBoardGameCheckOutLog();
        insert testRecord; 

        //Perform Test
        Test.startTest();
        List<BG_Checkout_Log__c> results = BGCheckOutLogSelector.newInstance().selectByLibraryEntryId(new Set<Id>{testRecord.BG_Library_Entry__c});
        Test.stopTest();

        //Validate Data
        Assert.areEqual(1, results.size(), 'No Results Returned for Test Record ID');
        Assert.areEqual(testRecord.Id, results[0].Id, 'Record Returned does not match Test Record');
    }

}