force-app/main/default/objects/BG_Checkout_Log__c/BG_Checkout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about each time a board game was checked out and back in</description>
    <label>Board Game Checkout Log</label>
    <nameField>
        <displayFormat>BGL-{000000}</displayFormat>
        <label>Board Game Checkout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Checkout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Checkout_Log__c/fields/BG_Library_Entry__c.field-meta.xml
<CustomField>
    <fullName>BG_Library_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library Entry</label>
    <referenceTo>BG_Library_Entry__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <description>Time Stamp Board Game was Checked In</description>
    <inlineHelpText>Time Stamp Board Game was Checked In</inlineHelpText>
    <label>Check In Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Time Stamp Board Game was Checked Out</description>
    <inlineHelpText>Time Stamp Board Game was Checked Out</inlineHelpText>
    <label>Check Out Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Checked_Out_By__c.field-meta.xml
<CustomField>
    <fullName>Checked_Out_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checked Out By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Library_Entry__c/BG_Library_Entry__c.object-meta.xml
<CustomObject>
    <description>Since a Board Game can be used in Many Events and Events can Have Many Board Games, this Object is used to Join the two Objects together</description>
    <label>Board Game Library Entry</label>
    <nameField>
        <displayFormat>BGLE-{000}</displayFormat>
        <label>Library Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Library Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/fflib-working-examples/main/schema/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/fflib-working-examples/main/classes/services/BGCheckOutLogService.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Service Class for the Board Game Check Out Log Object.
*
* Service Classes are where all of the method logic is completed. UnitOfWork Objects 
* as well as any other parameters are passed into each method as needed. A Config MDT record
* should exist for each Service Method.
*
* Service Classes Extend from a Base Service Class that houses the common logic for 
* retrieving and checking if services are enabled.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2025-01-09
* @modified       2025-02-13
* @systemLayer    Service
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
public inherited sharing class BGCheckOutLogService implements IBGCheckOutLogService {
    
    @TestVisible private static final String NO_BGLE_ID_ERR_MSG = 'Invalid Library Entry ID';
    @TestVisible private static final String NO_CHK_OUT_TIME_ERR_MSG = 'Check Out Time Required';
    @TestVisible private static final String FUTURE_CHK_OUT_TIME_ERR_MSG = 'Check Out Time Cannot be in the Future';
    @TestVisible private static final String NO_ATTENDEE_ID_ERR_MSG = 'Invalid Attendee ID';
    @TestVisible private static final String NO_LOG_ID_ERR_MSG = 'Invalid Check Out Log ID';
    @TestVisible private static final String NO_CHK_IN_TIME_ERR_MSG = 'Check In Time Required';
    @TestVisible private static final String INVALID_CHK_IN_TIME_ERR_MSG = 'Check In Time Cannot be Before Check Out Time';

    public void createCheckOutLog(fflib_SObjectUnitOfWork uow, Id bgleId, Id attendeeId, Datetime checkOutTime){
        //Validate Inputs
        if(bgleId == null || bgleId.getSObjectType() != BG_Library_Entry__c.getSObjectType()){
            throw new BGCheckOutLogServiceException(NO_BGLE_ID_ERR_MSG);
        }
        if(attendeeId == null || attendeeId.getSObjectType() != Event_Attendee__c.getSObjectType()){
            throw new BGCheckOutLogServiceException(NO_ATTENDEE_ID_ERR_MSG);
        }
        if(checkOutTime == null){
            throw new BGCheckOutLogServiceException(NO_CHK_OUT_TIME_ERR_MSG);
        }
        if(checkOutTime > System.now()){
            throw new BGCheckOutLogServiceException(FUTURE_CHK_OUT_TIME_ERR_MSG);
        }
        
        //Create Record
        BG_Checkout_Log__c log = new BG_Checkout_Log__c();
        log.BG_Library_Entry__c = bgleId;
        log.Checked_Out_By__c = attendeeId;
        log.Check_Out_Time__c = checkOutTime;
        uow.registerNew(log);
    }

    public void updateCheckOutLog(fflib_SObjectUnitOfWork uow, BG_Checkout_Log__c log, Datetime checkInTime){
        //Validate Inputs
        if(log == null || log.Id == null){
            throw new BGCheckOutLogServiceException(NO_LOG_ID_ERR_MSG);
        }
        if(checkInTime == null){
            throw new BGCheckOutLogServiceException(NO_CHK_IN_TIME_ERR_MSG);
        }
        if(checkInTime < log.Check_Out_Time__c){
            throw new BGCheckOutLogServiceException(INVALID_CHK_IN_TIME_ERR_MSG);
        }
        
        //Update Record
        log.Check_In_Time__c = checkInTime;
        uow.registerDirty(log);
    }

    public class BGCheckOutLogServiceException extends Exception {}
}