force-app/main/default/objects/BG_Checkout_Log__c/BG_Checkout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about each time a board game was checked out and back in</description>
    <label>Board Game Checkout Log</label>
    <nameField>
        <displayFormat>BGL-{000000}</displayFormat>
        <label>Board Game Checkout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Checkout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Checkout_Log__c/fields/BG_Library_Entry__c.field-meta.xml
<CustomField>
    <fullName>BG_Library_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library Entry</label>
    <referenceTo>BG_Library_Entry__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Check Out Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Checked_Out_By__c.field-meta.xml
<CustomField>
    <fullName>Checked_Out_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checked Out By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendee__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Total_Check_Out_Time_Formula__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_Out_Time_Formula__c</fullName>
    <description>Total Time the Board Game Was Checked Out</description>
    <formula>IF(ISNULL(Check_In_Time__c),   
       TIMEVALUE(NOW()) - TIMEVALUE(Check_Out_Time__c),
       TIMEVALUE(Check_In_Time__c) - TIMEVALUE(Check_Out_Time__c) 
)/60/1000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Time the Board Game Was Checked Out</inlineHelpText>
    <label>Total Check Out Time (in Min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Total_Check_Out_Time_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_Out_Time_Value__c</fullName>
    <description>Hidden Field That is Updated When Board Game is Checked Back In. Used to Calculate Average Time the Game is Checked Out.</description>
    <inlineHelpText>Updated When Board Game is Checked Back In. Used to Calculate Average Time the Game is Checked Out.</inlineHelpText>
    <label>Total Check Out Time (Hidden)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BG_Library_Entry__c/BG_Library_Entry__c.object-meta.xml
<CustomObject>
    <description>Since a Board Game can be used in Many Events and Events can Have Many Board Games, this Object is used to Join the two Objects together</description>
    <label>Board Game Library Entry</label>
    <nameField>
        <displayFormat>EBD-{000000}</displayFormat>
        <label>Library Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Library Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This Object holds information Attendees for the Event</description>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Services_Config__mdt/Services_Config__mdt.object-meta.xml
<CustomObject>
    <label>Services Config</label>
    <pluralLabel>Services Configs</pluralLabel>
</CustomObject>

force-app/main/default/classes/FFLIB Examples/Services/BGCheckOutLogService.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Service Class for the Board Game Check Out Log Object.
*
* Service Classes are where all of the method logic is completed. UnitOfWork Objects 
* as well as any other parameters are passed into each method as needed. A Config MDT record
* should exist for each Service Method.
*
* Service Classes Extend from a Base Service Class that houses the common logic for 
* retrieving and checking if services are enabled.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2025-01-09
* @modified       2025-02-13
* @systemLayer    Service
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
public without sharing class BGCheckOutLogService extends BaseService implements IBGCheckOutLogService {
    
    //Set Variables, Domains, and Selectors used throughout Service
    private BGCheckOutLogDomain domain;
    @TestVisible private static final String SERVICE_NOT_ENABLED_MSG = 'This Service is Not Enabled. Please Contact a System Administrator to Enable';
    @TestVisible private static final String NO_BGLE_ID_ERR_MSG = 'Invalid Library Entry ID';
    @TestVisible private static final String NO_CHK_OUT_TIME_ERR_MSG = 'Check Out Time Required';
    @TestVisible private static final String FUTURE_CHK_OUT_TIME_ERR_MSG = 'Check Out Time Cannot be in the Future';
    @TestVisible private static final String NO_ATTENDEE_ID_ERR_MSG = 'Invalid Attendee ID';
    @TestVisible private static final String NO_LOG_ID_ERR_MSG = 'Invalid Check Out Log ID';
    @TestVisible private static final String NO_CHK_IN_TIME_ERR_MSG = 'Check In Time Required';
    @TestVisible private static final String INVALID_CHK_IN_TIME_ERR_MSG = 'Check In Time Cannot be Before Check Out Time';

    //Initialize Service Class
    public static IBGCheckOutLogService newInstance(){
        return (IBGCheckOutLogService) Application.Service.newInstance(IBGCheckOutLogService.class);
    }

    public BGCheckOutLogService(){
        super('BGCheckOutLog'); //Calls the Constructor from the Parent Class
    }

    @TestVisible
    //Private Constructor for Testing to provide own Service Config
    private BGCheckOutLogService(List<Services_Config__mdt> configList){
        super(configList, 'BGCheckOutLog');  // Calls the protected constructor of BaseService with custom config list
    }

    //Abstract Method from Parent that Must be implemented
    protected override void initialize(){
        //Initialize Any Selectors through Application Layer 
        // so they can be Mocked and Stubbed from the Test Class
    }

    public void setTotalCheckOutTime(List<BG_Checkout_Log__c> records){
        setTotalCheckOutTime(records, null);
    }

    public void setTotalCheckOutTime(List<BG_Checkout_Log__c> records, Map<ID, SObject> existingRecords){
        
        domain = (BGCheckOutLogDomain) Application.Domain.newInstance(records);
        domain.setExistingRecords(existingRecords);

        //If Not Enabled, Do Nothing
        if(!this.serviceEnabled('setTotalCheckOutTime')){ //Check if this Service Method is Enabled from Parent
            return;
        }

        //Filter given Records to only those where Time In Value is Changed 
        records = domain.getChanged('Check_In_Time__c');
        //Filter Given Records to only those where Check Out Log is Completed
        records = domain.getCompletedCheckOutLogs(records);

        for(BG_Checkout_Log__c record : records){
            //Set Total_Check_Out_Time_Value__c field to equal the formula field Value
            record.Total_Check_Out_Time_Value__c = record.Total_Check_Out_Time_Formula__c;
        }
    }

    public void createCheckOutLog(fflib_SObjectUnitOfWork uow, Id bgleId, Id attendeeId, Datetime checkOutTime){
        //If Not Enabled, Throw Error
        if(!this.serviceEnabled('createCheckOutLog')){ //Check if this Service Method is Enabled from Parent
            throw new BGCheckOutLogServiceException(SERVICE_NOT_ENABLED_MSG);
        }
        //Validate Inputs
        if(bgleId == null || bgleId.getSObjectType() != BG_Library_Entry__c.getSObjectType()){
            throw new BGCheckOutLogServiceException(NO_BGLE_ID_ERR_MSG);
        }
        if(attendeeId == null || attendeeId.getSObjectType() != Event_Attendee__c.getSObjectType()){
            throw new BGCheckOutLogServiceException(NO_ATTENDEE_ID_ERR_MSG);
        }
        if(checkOutTime == null){
            throw new BGCheckOutLogServiceException(NO_CHK_OUT_TIME_ERR_MSG);
        }
        if(checkOutTime > System.now()){
            throw new BGCheckOutLogServiceException(FUTURE_CHK_OUT_TIME_ERR_MSG);
        }
        
        //Create Record
        BG_Checkout_Log__c log = new BG_Checkout_Log__c();
        log.BG_Library_Entry__c = bgleId;
        log.Checked_Out_By__c = attendeeId;
        log.Check_Out_Time__c = checkOutTime;
        uow.registerNew(log);
    }

    public void updateCheckOutLog(fflib_SObjectUnitOfWork uow, BG_Checkout_Log__c log, Datetime checkInTime){
        //If Not Enabled, Throw Error
        if(!this.serviceEnabled('updateCheckOutLog')){ //Check if this Service Method is Enabled from Parent
            throw new BGCheckOutLogServiceException(SERVICE_NOT_ENABLED_MSG);
        }
        //Validate Inputs
        if(log == null || log.Id == null){
            throw new BGCheckOutLogServiceException(NO_LOG_ID_ERR_MSG);
        }
        if(checkInTime == null){
            throw new BGCheckOutLogServiceException(NO_CHK_IN_TIME_ERR_MSG);
        }
        if(checkInTime < log.Check_Out_Time__c){
            throw new BGCheckOutLogServiceException(INVALID_CHK_IN_TIME_ERR_MSG);
        }
        
        //Update Record
        log.Check_In_Time__c = checkInTime;
        uow.registerDirty(log);
    }

    public class BGCheckOutLogServiceException extends Exception {}
}