force-app/main/default/objects/BG_Checkout_Log__c/BG_Checkout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about each time a board game was checked out and back in</description>
    <label>Board Game Checkout Log</label>
    <nameField>
        <displayFormat>BGL-{000000}</displayFormat>
        <label>Board Game Checkout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Checkout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <description>Time Stamp Board Game was Checked In</description>
    <inlineHelpText>Time Stamp Board Game was Checked In</inlineHelpText>
    <label>Check In Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Time Stamp Board Game was Checked Out</description>
    <inlineHelpText>Time Stamp Board Game was Checked Out</inlineHelpText>
    <label>Check Out Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Total_Check_Out_Time_Formula__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_Out_Time_Formula__c</fullName>
    <description>Total Time the Board Game Was Checked Out</description>
    <formula>IF(ISNULL(Check_In_Time__c),   
       TIMEVALUE(NOW()) - TIMEVALUE(Check_Out_Time__c),
       TIMEVALUE(Check_In_Time__c) - TIMEVALUE(Check_Out_Time__c) 
)/60/1000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Time the Board Game Was Checked Out</inlineHelpText>
    <label>Total Check Out Time (in Min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Total_Check_Out_Time_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Check_Out_Time_Value__c</fullName>
    <description>Hidden Field That is Updated When Board Game is Checked Back In. Used to Calculate Average Time the Game is Checked Out.</description>
    <inlineHelpText>Updated When Board Game is Checked Back In. Used to Calculate Average Time the Game is Checked Out.</inlineHelpText>
    <label>Total Check Out Time (Hidden)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/classes/actions/SetTotalCheckoutTimeBeforeAction.cls
public without sharing class SetTotalCheckoutTimeBeforeAction extends AbstractBaseDomainProcessAction {
    public override void runInProcess(){

        List<BG_Checkout_Log__c> filteredRecords = (List<BG_Checkout_Log__c>) getChanged('Check_In_Time__c');

        for (BG_Checkout_Log__c record : filteredRecords){
            //If Either Check Out Time or Check In Time are Have a value,
            // and Check In Time is LATER than Check Out Time,
            if (validateTimeOutValue(record) 
                && record.Check_In_Time__c != null ){
                    //Set Total_Check_Out_Time_Value__c field to equal the formula field Value
                    record.Total_Check_Out_Time_Value__c = record.Total_Check_Out_Time_Formula__c;
                }
        }
    }

    private Boolean validateTimeOutValue(BG_Checkout_Log__c record){
        //If Check Out is Null, Return false
        if(record.Check_Out_Time__c == null){
            return false;
        }
        //If Check In is Not Null and is Sooner than the Check Out Time, Return False
        if(record.Check_In_Time__c != null
            && record.Check_Out_Time__c > record.Check_In_Time__c){
            return false;
        }
        //If Check Out Time is Not Null and Check In Time is Null, return True
        //If Check Out Time is Not Null and Check In Time is LATER than Check Out Time, return True
        return true;
    }
}