force-app/main/default/objects/BG_Checkout_Log__c/BG_Checkout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about each time a board game was checked out and back in</description>
    <label>Board Game Checkout Log</label>
    <nameField>
        <displayFormat>BGL-{000000}</displayFormat>
        <label>Board Game Checkout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Checkout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Attendee_Name__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Name__c</fullName>
    <formula>Checked_Out_By__r.Attendee_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attendee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/BG_Library_Entry__c.field-meta.xml
<CustomField>
    <fullName>BG_Library_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Library Entry</label>
    <referenceTo>BG_Library_Entry__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Board_Game_Name__c.field-meta.xml
<CustomField>
    <fullName>Board_Game_Name__c</fullName>
    <formula>BG_Library_Entry__r.Board_Game__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Board Game Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Check Out Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Checked_Out_By__c.field-meta.xml
<CustomField>
    <fullName>Checked_Out_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checked Out By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BG_Checkout_Log__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Board Game Checkout Logs</relationshipLabel>
    <relationshipName>Board_Game_Checkout_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Checkout_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+ BG_Library_Entry__r.Event__r.Id,  BG_Library_Entry__r.Event__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BG_Library_Entry__c/BG_Library_Entry__c.object-meta.xml
<CustomObject>
    <description>Since a Board Game can be used in Many Events and Events can Have Many Board Games, this Object is used to Join the two Objects together</description>
    <label>Board Game Library Entry</label>
    <nameField>
        <displayFormat>EBD-{000000}</displayFormat>
        <label>Library Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Game Library Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BG_Library_Entry__c/fields/Board_Game__c.field-meta.xml
<CustomField>
    <fullName>Board_Game__c</fullName>
    <label>Board Game</label>
    <referenceTo>Board_Games__c</referenceTo>
    <relationshipLabel>Event Board Games</relationshipLabel>
    <relationshipName>Event_Board_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Library_Entry__c/fields/Board_Game_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Board_Game_Image_URL__c</fullName>
    <formula>Board_Game__r.Image_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Board Game Image URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Library_Entry__c/fields/BoardGameName__c.field-meta.xml
<CustomField>
    <fullName>BoardGameName__c</fullName>
    <formula>Board_Game__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BoardGameName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BG_Library_Entry__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Board Games</relationshipLabel>
    <relationshipName>Event_Board_Games</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/BG_Library_Entry__c/fields/Event_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Logo_URL__c</fullName>
    <formula>Event__r.Event_Image_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Logo URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BG_Library_Entry__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <formula>Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This is the Description for the Event Object</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FFLIB Examples/Selectors/BGCheckOutLogSelector.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Selector for the Board Game Check Out Log Object
*
* Selectors are reusable classes that perform all of the SOQL calls for an application.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2025-02-05
* @modified       2025-02-05
* @systemLayer    Selector
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@SuppressWarnings('PMD.SOQLInjection') //PMD Incorrectly identifies Queries made in Selectors to have possible SOQL Injection. This Suppresses that Warning
//Without Sharing is needed in order to always return all values of a query
public without sharing class BGCheckOutLogSelector extends fflib_SObjectSelector implements IBGCheckOutLogSelector {
    //Required Method to Initialize Selector
    public static IBGCheckOutLogSelector newInstance() {
        return (IBGCheckOutLogSelector) Application.Selector.newInstance(BG_Checkout_Log__c.SObjectType);
    }

    //Required Method to Determine SObject Type
    public Schema.SObjectType getSObjectType() {
        return BG_Checkout_Log__c.SObjectType;
    }

    //Required Method. Used to get Fields from Object needed in any Selector Method
    //Add Fields to List as Needed.
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            BG_Checkout_Log__c.Id,
            BG_Checkout_Log__c.Attendee_Name__c,
            BG_Checkout_Log__c.BG_Library_Entry__c,
            BG_Checkout_Log__c.Board_Game_Name__c,
            BG_Checkout_Log__c.Check_Out_Time__c,
            BG_Checkout_Log__c.Check_In_Time__c,
            BG_Checkout_Log__c.Event_Name__c            
        };
    }
    
    //Standard Method. Basic Select By ID Query (From Parent fflib_SObjectSelector)
    public List<BG_Checkout_Log__c> selectById(Set<Id> recordIds){
        // Optionally, this method can just use and return the line:
            // return super.selectSObjectsById(recordIds);

        //If Any Customization is needed for this method, replace this with a normal QueryFactory Query
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('BG_Library_Entry__r.BoardGameName__c');
        query.selectField('BG_Library_Entry__r.Board_Game_Image_URL__c');
        query.selectField('BG_Library_Entry__r.Event__r.Name');
        query.selectField('BG_Library_Entry__r.Event_Logo_URL__c');
        query.selectField('Checked_Out_By__r.Attendee_Name__c');
        query.setCondition('Id = :recordIds');
        return (List<BG_Checkout_Log__c>) Database.query(query.toSOQL());

    }
    
    //Names of Selector Methods Should describe all of the Conditions for the Query
    //Return Value should always be a List of the Selector's Object
    //Input Parameters should always be Sets of the value type for bulkificationa and resuability
    public List<BG_Checkout_Log__c> selectByBoardGameId(Set<Id> boardGameIds){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('BG_Library_Entry__r.BoardGameName__c');
        query.selectField('BG_Library_Entry__r.Board_Game_Image_URL__c');
        query.selectField('BG_Library_Entry__r.Event__r.Name');
        query.selectField('BG_Library_Entry__r.Event_Logo_URL__c');
        query.selectField('Checked_Out_By__r.Attendee_Name__c');
        query.setCondition('BG_Library_Entry__r.Board_Game__c = :boardGameIds');
        return (List<BG_Checkout_Log__c>) Database.query(query.toSOQL());
    }

    public List<BG_Checkout_Log__c> selectByLibraryEntryId(Set<Id> bgleIds){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('BG_Library_Entry__r.BoardGameName__c');
        query.selectField('BG_Library_Entry__r.Board_Game_Image_URL__c');
        query.selectField('BG_Library_Entry__r.Event__r.Name');
        query.selectField('BG_Library_Entry__r.Event_Logo_URL__c');
        query.selectField('Checked_Out_By__r.Attendee_Name__c');
        query.setCondition('BG_Library_Entry__c = :bgleIds');
        return (List<BG_Checkout_Log__c>) Database.query(query.toSOQL());
    }

}