force-app/main/default/objects/Board_Games__c/Board_Games__c.object-meta.xml
<CustomObject>
    <description>This Object holds information about Individual Board Games.</description>
    <label>Board Game</label>
    <nameField>
        <label>Board Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Games__c/fields/Avg_Rating__c.field-meta.xml
<CustomField>
    <fullName>Avg_Rating__c</fullName>
    <label>Avg. Rating</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Avg_Weight__c.field-meta.xml
<CustomField>
    <fullName>Avg_Weight__c</fullName>
    <label>Avg. Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/BGG_ID__c.field-meta.xml
<CustomField>
    <fullName>BGG_ID__c</fullName>
    <label>BGG ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>Image URL for Board Game provided By BoardGameGeek</description>
    <inlineHelpText>Image URL for Board Game provided By BoardGameGeek</inlineHelpText>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Max_Players__c.field-meta.xml
<CustomField>
    <fullName>Max_Players__c</fullName>
    <label>Max Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Mechanics__c.field-meta.xml
<CustomField>
    <fullName>Mechanics__c</fullName>
    <label>Mechanics</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Min_Age__c.field-meta.xml
<CustomField>
    <fullName>Min_Age__c</fullName>
    <description>Recommended Minimum Age of Players for Board Game provided by BoardGameGeek</description>
    <inlineHelpText>Recommended Minimum Age of Players for Board Game provided by BoardGameGeek</inlineHelpText>    
    <label>Min Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Min_Players__c.field-meta.xml
<CustomField>
    <fullName>Min_Players__c</fullName>
    <label>Min Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Playing_Time__c.field-meta.xml
<CustomField>
    <fullName>Playing_Time__c</fullName>
    <label>Playing Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Board_Games__c/fields/Year_Published__c.field-meta.xml
<CustomField>
    <fullName>Year_Published__c</fullName>
    <label>Year Published</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FFLIB Examples/Selectors/BoardGameSelector.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Selector for the Board Game Object
*
* Selectors are reusable classes that perform all of the SOQL calls for an application.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2024-11-30
* @modified       2024-11-30
* @systemLayer    Selector
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@SuppressWarnings('PMD.SOQLInjection') //PMD Incorrectly identifies Queries made in Selectors to have possible SOQL Injection. This Suppresses that Warning
//Without Sharing is needed in order to always return all values of a query
public without sharing class BoardGameSelector extends fflib_SObjectSelector implements IBoardGameSelector  {
    
    //Required Method to Initialize Selector
    public static IBoardGameSelector newInstance() {
        return (IBoardGameSelector) Application.Selector.newInstance(Board_Games__c.SObjectType);
    }

    //Required Method to Determine SObject Type
    public Schema.SObjectType getSObjectType() {
        return Board_Games__c.SObjectType;
    }

    //Required Method. Used to get Fields from Object needed in any Selector Method
    //Add Fields to List as Needed.
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Board_Games__c.Name,
            Board_Games__c.BGG_ID__c,
            Board_Games__c.Is_New__c,
            //Need to add fields in order to compare values
            Board_Games__c.Avg_Rating__c,
            Board_Games__c.Avg_Weight__c,
            Board_Games__c.Image_URL__c,
            Board_Games__c.Thumbnail_URL__c,
            Board_Games__c.Max_Players__c,
            Board_Games__c.Min_Players__c,
            Board_Games__c.Min_Age__c,
            Board_Games__c.Playing_Time__c,
            Board_Games__c.Year_Published__c,
            Board_Games__c.Publisher__c,
            Board_Games__c.Categories__c,
            Board_Games__c.Mechanics__c
        };
    }
    
    //Standard Method. Basic Select By ID Query (From Parent fflib_SObjectSelector)
    public List<Board_Games__c> selectById(Set<Id> recordIds){
        // Optionally, this method can just use and return the line:
        return super.selectSObjectsById(recordIds);
        //If Any Customization is needed for this method, replace this with a normal QueryFactory Query
    }
    
    //Names of Selector Methods Should describe all of the Conditions for the Query
    //Return Value should always be a List of the Selector's Object
    //Input Parameters should always be Sets of the value type for bulkificationa and resuability
    public List<Board_Games__c> selectByBGGIDs(Set<String> bggIDs){

        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('BGG_ID__c = :bggIDs');
        return (List<Board_Games__c>) Database.query(query.toSOQL());
    }
}