sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Avg_Weight__c.field-meta.xml
<CustomField>
    <fullName>Avg_Weight__c</fullName>
    <description>Average Complexity provided by BoardGameGeek. On a Scale of 1 to 5, where 5 is the most Complex</description>
    <inlineHelpText>Average Complexity provided by BoardGameGeek. On a Scale of 1 to 5, where 5 is the most Complex</inlineHelpText>
    <label>Avg. Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/BGG_ID__c.field-meta.xml
<CustomField>
    <fullName>BGG_ID__c</fullName>
    <description>This is the Unique ID given by BoardGameGeek for this Board Game. Used for matching Board Game Records when importing from BGG</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Unique ID given by BoardGameGeek for this Board Game. Used for matching Board Game Records when importing from BGG</inlineHelpText>
    <label>BGG ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Is_New__c.field-meta.xml
<CustomField>
    <fullName>Is_New__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Enabled, this Board Game was recently added in the last import</description>
    <inlineHelpText>If Enabled, this Board Game was recently added in the last import</inlineHelpText>
    <label>Is New</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Max_Players__c.field-meta.xml
<CustomField>
    <fullName>Max_Players__c</fullName>
    <description>Maximium Number of Players for Board Game provided by BoardGameGeek</description>
    <inlineHelpText>Maximium Number of Players for Board Game provided by BoardGameGeek</inlineHelpText>
    <label>Max Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Mechanics__c.field-meta.xml
<CustomField>
    <fullName>Mechanics__c</fullName>
    <description>List of Board Game Mechanics for Board Game provided By BoardGameGeek</description>
    <inlineHelpText>List of Board Game Mechanics for Board Game provided By BoardGameGeek</inlineHelpText>
    <label>Mechanics</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Min_Players__c.field-meta.xml
<CustomField>
    <fullName>Min_Players__c</fullName>
    <description>Minimum Players for Board Game provided by BoardGameGeek</description>
    <inlineHelpText>Minimum Players for Board Game provided by BoardGameGeek</inlineHelpText>
    <label>Min Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/fflib-working-examples/main/schema/objects/Board_Game__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <description>Thumbnail Image URL for Board Game provided By BoardGameGeek</description>
    <inlineHelpText>Thumbnail Image URL for Board Game provided By BoardGameGeek</inlineHelpText>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/fflib-working-examples/main/classes/selectors/BoardGameSelector.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Selector for the Board Game Object
*
* Selectors are reusable classes that perform all of the SOQL calls for an application.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sean Riley
* @modifiedBy     Sean Riley
* @version        1.0
* @created        2024-11-30
* @modified       2024-11-30
* @systemLayer    Selector
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@SuppressWarnings('PMD.SOQLInjection') //PMD Incorrectly identifies Queries made in Selectors to have possible SOQL Injection. This Suppresses that Warning
//Without Sharing is needed in order to always return all values of a query
public without sharing class BoardGameSelector extends ApplicationSObjectSelector implements IBoardGameSelector  {
    
    //Required Method to Initialize Selector
    public static IBoardGameSelector newInstance() {
        return (IBoardGameSelector) Application.Selector.newInstance(Board_Game__c.SObjectType);
    }

    //Required Method to Determine SObject Type
    public Schema.SObjectType getSObjectType() {
        return Board_Game__c.SObjectType;
    }

    //Required Method. Replaces Abstract method in parent class.
    //Used to get Addtional Custom Fields from Object used in any Selector Method.
    //All Standard Fields already included
    //Add Fields to List as Needed.
    public List<Schema.SObjectField> getAdditionalSObjectFieldList() {
        return new List<Schema.SObjectField> {
            // Board_Game__c.BGG_ID__c,
            // Board_Game__c.Is_New__c,
            // //Need to add fields in order to compare values
            // Board_Game__c.Avg_Rating__c,
            // Board_Game__c.Avg_Weight__c,
            // Board_Game__c.Image_URL__c,
            // Board_Game__c.Thumbnail_URL__c,
            // Board_Game__c.Max_Players__c,
            // Board_Game__c.Min_Players__c,
            // Board_Game__c.Min_Age__c,
            // Board_Game__c.Playing_Time__c,
            // Board_Game__c.Year_Published__c,
            // Board_Game__c.Publisher__c,
            // Board_Game__c.Categories__c,
            // Board_Game__c.Mechanics__c
        };
    }
    
    //Standard Method. Basic Select By ID Query (From Parent fflib_SObjectSelector)
    public List<Board_Game__c> selectById(Set<Id> recordIds){
        // Optionally, this method can just use and return the line:
        return super.selectSObjectsById(recordIds);
        //If Any Customization is needed for this method, replace this with a normal QueryFactory Query
    }
    
    //Names of Selector Methods Should describe all of the Conditions for the Query
    //Return Value should always be a List of the Selector's Object
    //Input Parameters should always be Sets of the value type for bulkificationa and resuability
    public List<Board_Game__c> selectByBGGIDs(Set<String> bggIDs){

        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('BGG_ID__c = :bggIDs');
        return (List<Board_Game__c>) Database.query(query.toSOQL());
    }
}